version: '3.8'
services:
  heartbeat:
    container_name: nillion
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.10-slim
        ARG NIL_SDK_VERSION
        ARG DEBIAN_FRONTEND="noninteractive"
        ENV PUID=1000
        ENV PGID=1000
        SHELL ["/bin/bash", "-o", "pipefail", "-xe", "-c"]
        RUN apt update; \
            apt install -y --no-install-recommends \
                bash jq curl git build-essential; \
            apt clean; \
            rm -rf /var/lib/apt/lists/*; \
            pip install --upgrade pip; \
            groupadd --gid 1000 -r nillion; \
            useradd -rm -g nillion --shell /bin/bash --uid 1000 --gid 1000 nillion;
        USER nillion
        RUN { curl -L https://foundry.paradigm.xyz | bash ; } && \
          /home/nillion/.foundry/bin/foundryup
        RUN curl -L https://nilup.nilogy.xyz/install.sh | bash; \
          /home/nillion/.nilup/bin/nilup init; \
          /home/nillion/.nilup/bin/nilup install $${NIL_SDK_VERSION}; \
          /home/nillion/.nilup/bin/nilup use $${NIL_SDK_VERSION};
        RUN  pip install nada-dsl==$${NIL_SDK_VERSION}; \
             pip install py-nillion-client==$${NIL_SDK_VERSION};
        RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
        RUN /home/nillion/.cargo/bin/cargo install --git https://github.com/wwwehr/libp2p-lookup.git --branch feature/keypair-file;
      args:
        - NIL_SDK_VERSION=0.2.1
    network_mode: 'bridge'
    environment:
      - TZ=Europe/London
      - PATH=/home/nillion/.local/bin:/home/nillion/.foundry/bin:/home/nillion/.nilup/bin:/home/nillion/.nillion/bin:/home/nillion/.cargo/bin:${PATH}
    volumes:
      - '$PWD/../../:/host'
      - '$HOME/nillion-node.key:/opt/nillion-node.key'
    working_dir: /host
    command:
      - /bin/bash
      - '-c'
      - |
        /host/tools/test-remote-network.sh /opt/nillion-node.key
