version: '3.8'
services:
  demo:
    container_name: nillion
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.10-slim
        ARG NIL_SDK_VERSION
        ARG DEBIAN_FRONTEND="noninteractive"
        ENV PUID=1000
        ENV PGID=1000
        SHELL ["/bin/bash", "-o", "pipefail", "-xe", "-c"]
        RUN apt update; \
            apt install -y --no-install-recommends \
                bash jq curl git; \
            apt clean; \
            rm -rf /var/lib/apt/lists/*; \
            pip install --upgrade pip; \
            groupadd --gid 1000 -r nillion; \
            useradd -rm -g nillion --shell /bin/bash --uid 1000 --gid 1000 nillion;
        USER nillion
        RUN curl -L https://nilup.nilogy.xyz/install.sh | bash; \
          /home/nillion/.nilup/bin/nilup init; \
          /home/nillion/.nilup/bin/nilup install $${NIL_SDK_VERSION}; \
          /home/nillion/.nilup/bin/nilup use $${NIL_SDK_VERSION};
        RUN  pip install nada-dsl==$${NIL_SDK_VERSION}; \
             pip install py-nillion-client==$${NIL_SDK_VERSION};
      args:
        - NIL_SDK_VERSION=0.4.0
    network_mode: 'bridge'
    environment:
      - TZ=Europe/London
      - PATH=/home/nillion/.local/bin:/home/nillion/.nilup/bin:/home/nillion/.nillion/bin:${PATH}
    volumes:
      - '$PWD/..:/host'
    working_dir: /host
    command:
      - /bin/bash
      - '-c'
      - |
        { nohup nillion-devnet & } && \
        echo 'waiting for network...' && \
        sleep 10 && \
        pushd compute-basic && \
        pip install -r requirements.txt && \
        python3 client.py
