payments:
  rpc_endpoint: https://rpc-endpoint.testnet-photon.nilogy.xyz/
  signer:
    wallet:
      chain_id: 22255222
      private_key: b4840879641631a0231629fcb8bc0f3a6f59375d112a007c9cab6fd3b3e66dab
  smart_contract_addresses:
    blinding_factors_manager: 0xf66cb23aa5857ae1d34a23ce385fa78495c50c69
    payments: 0xc166ce8bfc56e4493ffd43a99db234a9f0413443

bootnodes:
  - /dns/node-1.testnet-photon.nillion-network.nilogy.xyz/tcp/14111/p2p/12D3KooWCfFYAb77NCjEk711e9BVe2E6mrasPZTtAjJAPtVAdbye
  - /dns/node-2.testnet-photon.nillion-network.nilogy.xyz/tcp/14111/p2p/12D3KooWCcii8jb8ggJH8e3YeYFrKhrskc4NpxEEuTH6r2Zxg4Av

clusters:
  - id: b13880d3-dde8-4a75-a171-8a1a9d985e6c
