cluster_id: f592f8ea-7651-4ab8-b692-ef149b783dc9
payments_config:                                                                                                 
  rpc_endpoint: https://rpc-endpoint.testnet-fe.nilogy.xyz
  signer:                                                                                                 
    wallet:                                                                                               
      chain_id: 22255222                                                                                  
      private_key: YOUR_FUNDED_PRIVATE_KEY
  smart_contract_addresses:                                                                               
    blinding_factors_manager: "0xa841c8814aae50790f79b5bfa6c5ecd25071655e"
    payments: "0x27303ed96fdf3986413c2e0879f7b1a9b17ee7f5"
bootnodes_ws:
    - "/dns/node-1.testnet-fe.nillion-network.nilogy.xyz/tcp/14211/wss/p2p/12D3KooWNbB2dobuVpH5qetmWnamsKr1G9rC5Sbvj2UsMt3jvQxK"
bootnodes:
    - "/dns/node-1.testnet-fe.nillion-network.nilogy.xyz/tcp/14111/p2p/12D3KooWNbB2dobuVpH5qetmWnamsKr1G9rC5Sbvj2UsMt3jvQxK"
