payments:                                                                                                 
  rpc_endpoint: https://rpc-endpoint.testnet-fe.nilogy.xyz
  signer:                                                                                                 
    wallet:                                                                                               
      chain_id: 22255222                                                                                  
      private_key: b4840879641631a0231629fcb8bc0f3a6f59375d112a007c9cab6fd3b3e66dab                       
  smart_contract_addresses:                                                                               
    blinding_factors_manager: '0xb8e5262d089364c74118d6756befc0f5454606cb'                                
    payments: '0xfd7675220b7f700507c7f618c26bc9f2bbd46d8e'                                                
bootnodes:
    - /dns/node-1.testnet-fe.nillion-network.nilogy.xyz/tcp/14111/p2p/12D3KooWNbB2dobuVpH5qetmWnamsKr1G9rC5Sbvj2UsMt3jvQxK 
    - /dns/node-2.testnet-fe.nillion-network.nilogy.xyz/tcp/14111/p2p/12D3KooWHuSKUJyDZsZf1WVLbjstej6yrcj1Wm1SspvFTKYiLY4J

clusters:
  - id: f592f8ea-7651-4ab8-b692-ef149b783dc9
